# List your RSS feeds here
sections:

    - name: General News
      items:
        - nytimes.com

    - name: Tech News
      items:
        - techcrunch.com
        - slashdot.org

# Configure the email sending options here
mailer:
    to_address:      <your kindle email address>
    from_address:    <a whitelisted source email address>
    delivery_method: :smtp
    options:
        address:                smtp.gmail.com
        port:                   587
        domain:                 gmail.com
        authentication:         :login
        user_name:              <your gmail username>
        password:               <your gmail password>